Add discovery of Yeelight devices
florian-mollin/yapi pull request #1
Opened 2018-09-13 13:25 UTC by valashko

This pull request makes it possible to discover multiple Yeelight devices and store additional information such as id, firmware version etc.

2018-09-28 13:14 UTC, viktorteren approved these changes
I tried these changes, works great

2018-09-30 11:19 UTC, florian-mollin commented
Thanks for your PR!
As you can see, this repo is a little bit "inactive" and I don't really spend much time maintaining it anymore, but it's an important PR.
I will review your code and make some comments for the "debate" and progress for merge this PR

2018-09-30 11:38 UTC, florian-mollin requested changes
- There are some changes to be made (see review).
- Maybe remove `meta` attribute from `YeelightDevice` class (user can retrieve information with your `YeelightDeviceMeta` class)
- Maybe add some tests as far as possible
- I have not yet tested the code

2018-09-30 11:38 UTC, florian-mollin commented on README.md
> +ArrayList<YeelightDevice> devices = new ArrayList<>();
Maybe use `List` instead `ArrayList`

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDevice.java
> +    private Optional<YeelightDeviceMeta> meta;
I'm not a huge fan for a "meta" attribute (for example if you instanciate a Bulb with only IP address, there is no "meta" information)

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDevice.java
> +    public YeelightDeviceMeta getMeta() {
If we keep "meta", getter must return an Optional and not a default meta with empty attributes

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDeviceMeta.java
> +public class YeelightDeviceMeta {
Maybe some JavaDoc ?

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +public class YeelightDiscoveryManager {
I think it's a singleton ? So use design pattern singleton

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +
Why new line here ?

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +    public static Set<YeelightDeviceMeta> search() throws IOException {
Some javadoc ?

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +public class YeelightDiscoveryManager {
javadoc ?

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +public class YeelightDiscoveryManager {
This code is yours? If no, cite the author (in javadoc ?)

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +        HashSet<YeelightDeviceMeta> devices = new HashSet<>(); // prevent duplicates as a result of multiple responses from the same device
Use `Set` instead `HashSet`

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +                byte[] responseBuffer = new byte[1500];
`1500` ?

2018-09-30 11:38 UTC, florian-mollin commented on src/main/java/com/mollin/yapi/YeelightDiscoveryManager.java
> +        // TODO response validation
TODO here

2020-03-09 21:11 UTC, florian-mollin commented
It's been a long time, I think I can close this PR

2020-03-09 21:11 UTC, closed without merging